### ISSUE TITLE
2015.06 pre2: error when booting up from usb

### ISSUE THREAD

**Issue by star-buck** [netrunner-rolling/manjaro-tools-netrunner-overlays#1]
mount: /bootmnt/netrunner_rolling/x86_64/livecd-image.sqfs is not a block device

**Comment by NuLogicSystems** [comment]
There where some permission issues that needed to be fixed and some .directory files that needed to be removed in my manjaro-tools profiles before running buildiso that I noticed I had missed when I tested the 32 bit RC2 local build. I had already started uploading a RC2  so I stopped the upload when I realized what had happened, I most have forgot to delete it before I fell asleep last night. I do apologize for that.
