### ISSUE TITLE
Steam native pacakge

### ISSUE THREAD

**Issue by alexandruianu** [netrunner-rolling/manjaro-tools-netrunner-overlays#2]
Hey there, Manjaro's Steam maintainer here. If you want to readd the Steam in native library mode to show up by default in an install, you need to add the steam-native package to the package list.

We've refrained from doing that because it's just a simple package install and it replaces a couple of basic Arch lib32 packages with Valve versions, but add it if you wish to make it available for ease of use.

**Comment by NuLogicSystems** [comment]
No, I think I'll leave it out for now as well.
Thanks though.
